# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-04 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapperinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='scrapperinformation',
            name='web_url',
            field=models.URLField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
