# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20180304_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapperinformation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
